<a href="https://colab.research.google.com/github/Akashrathor4/python_language/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
w1,w2,w3 = 0.3,0.2,0.5

In [ ]:
kanto_temp = 73
kanto_rainfall = 67
kanto_humidity = 43

In [ ]:
kanto_yield_apple = w1*kanto_temp + w2*kanto_rainfall + w3*kanto_humidity
kanto_yield_apple

56.8

In [ ]:
kanto = [73,67,43]
johto = [91,88,64]
hoenn = [87,134,58]
sinnoh = [102,43,37]
unova = [69,96,70]

In [ ]:
weights = [w1,w2,w3]

In [ ]:
%%time
def crop_yield(region,weights):
  result = 0
  for x,w in zip(region,weights):
    result += x*w
  # for i in range(len(region)):
  #   result += region[i]*weights[i]
  return result

CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 7.15 µs


In [ ]:
crop_yield(kanto,weights)

56.8

In [ ]:

crop_yield(johto,weights)

76.9

In [ ]:
crop_yield(hoenn,weights)

81.9

In [ ]:
crop_yield(sinnoh,weights)

57.699999999999996

In [ ]:
crop_yield(unova,weights)
#

74.9

In [ ]:
import numpy as np



In [ ]:
kanto = np.array([73,67,43])

In [ ]:
kanto

array([73, 67, 43])

In [ ]:
type(kanto)

numpy.ndarray

In [ ]:
kanto.dtype

dtype('int64')

In [ ]:
kanto.ndim

1

In [ ]:
kanto.shape

(3,)

In [ ]:
weights =  np.array([w1,w2,w3])

In [ ]:
weights

array([0.3, 0.2, 0.5])

In [ ]:
weights[0]


np.float64(0.3)

In [ ]:
float(np.dot(kanto,weights))


56.8

In [ ]:
np.dot(kanto, weights).item()


56.8

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

In [ ]:
arr3 = arr1*arr2

In [ ]:
arr3

array([ 4, 10, 18])

In [ ]:
int(arr3.sum())

32

In [ ]:
int(np.dot(arr1,arr2))

32

In [ ]:
%%time
(kanto*weights).sum()

CPU times: user 65 µs, sys: 8 µs, total: 73 µs
Wall time: 87.7 µs


np.float64(56.8)

In [ ]:
climate_data = np.array([[73,67,43],
                         [91,88,64],
                         [87,134,58],
                         [102,43,37],
                         [69,96,70]])

In [ ]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [ ]:
climate_data.shape

(5, 3)

In [ ]:
weights

array([0.3, 0.2, 0.5])

In [ ]:
weights.shape

(3,)

In [ ]:
arr3 = np.array([
    [[11,12,13],
     [13,14,15]],
    [[15,16,17],
     [17,18,19.5]]
])

In [ ]:
arr3.shape

(2, 2, 3)

In [ ]:
climate_data.dtype

dtype('int64')

In [ ]:
arr3.dtype

dtype('float64')

In [ ]:
np.matmul(climate_data,weights)

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [ ]:
climate_data @ weights

array([56.8, 76.9, 81.9, 57.7, 74.9])

writting and reading operation by  **numpy**

In [ ]:
climate_data = np.genfromtxt("/content/climate_data.txt",delimiter=",", skip_header=1)

In [ ]:
climate_data

array([[ 11.88,  30.28,  95.76],
       [ 33.58,  90.52,  25.37],
       [ 40.  , 281.4 ,  96.72],
       ...,
       [ 24.12,  92.56,  91.46],
       [ 11.19,  11.17,  63.22],
       [ 37.47,  85.79,  56.87]])

In [ ]:
climate_data.size

30000

In [ ]:
climate_data.shape

(10000, 3)

In [ ]:
weights

array([0.3, 0.2, 0.5])

In [ ]:
yields = climate_data @ weights

In [ ]:
yields

array([ 57.5  ,  40.863, 116.64 , ...,  71.478,  37.201,  56.834])

In [ ]:
yields.shape

(10000,)

In [ ]:
help(np.concatenate)

Help on _ArrayFunctionDispatcher in module numpy:

concatenate(...)
    concatenate(
        (a1, a2, ...),
        axis=0,
        out=None,
        dtype=None,
        casting="same_kind"
    )

    Join a sequence of arrays along an existing axis.

    Parameters
    ----------
    a1, a2, ... : sequence of array_like
        The arrays must have the same shape, except in the dimension
        corresponding to `axis` (the first, by default).
    axis : int, optional
        The axis along which the arrays will be joined.  If axis is None,
        arrays are flattened before use.  Default is 0.
    out : ndarray, optional
        If provided, the destination to place the result. The shape must be
        correct, matching that of what concatenate would have returned if no
        out argument were specified.
    dtype : str or dtype
        If provided, the destination array will have this dtype. Cannot be
        provided together with `out`.

        .. versionadded:: 1.20.0

    c

In [ ]:
climate_results = np.concatenate((climate_data,yields.reshape(10000,1)),axis=1)

In [ ]:
climate_results

array([[ 11.88 ,  30.28 ,  95.76 ,  57.5  ],
       [ 33.58 ,  90.52 ,  25.37 ,  40.863],
       [ 40.   , 281.4  ,  96.72 , 116.64 ],
       ...,
       [ 24.12 ,  92.56 ,  91.46 ,  71.478],
       [ 11.19 ,  11.17 ,  63.22 ,  37.201],
       [ 37.47 ,  85.79 ,  56.87 ,  56.834]])

In [ ]:
help(np.reshape)

Help on _ArrayFunctionDispatcher in module numpy:

reshape(a, newshape, order='C')
    Gives a new shape to an array without changing its data.

    Parameters
    ----------
    a : array_like
        Array to be reshaped.
    newshape : int or tuple of ints
        The new shape should be compatible with the original shape. If
        an integer, then the result will be a 1-D array of that length.
        One shape dimension can be -1. In this case, the value is
        inferred from the length of the array and remaining dimensions.
    order : {'C', 'F', 'A'}, optional
        Read the elements of `a` using this index order, and place the
        elements into the reshaped array using this index order.  'C'
        means to read / write the elements using C-like index order,
        with the last axis index changing fastest, back to the first
        axis index changing slowest. 'F' means to read / write the
        elements using Fortran-like index order, with the first index
     

In [ ]:
np.savetxt("climate_results.txt",
           climate_results,
           fmt="%.2f",
           delimiter=",",
           header="temperature,rainfall,humidity,yield_apples",
           )

In [ ]:
arr2 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

In [ ]:
arr3 = np.array([[11,12,13],
                [14,15,16],
                [17,18,19]])

In [ ]:
arr2 + 3

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
arr3 - arr2

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [ ]:
arr2 / 2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

In [ ]:
arr2*arr3

array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

In [ ]:
arr2%4

array([[1, 2, 3],
       [0, 1, 2],
       [3, 0, 1]])

In [ ]:
arr2/arr3

array([[0.09090909, 0.16666667, 0.23076923],
       [0.28571429, 0.33333333, 0.375     ],
       [0.41176471, 0.44444444, 0.47368421]])

In [ ]:
arr4 = np.array([4,5,6])

In [ ]:
arr2.shape

(3, 3)

In [ ]:
arr4.shape

(3,)

In [ ]:
arr2 + arr4

array([[ 5,  7,  9],
       [ 8, 10, 12],
       [11, 13, 15]])

In [ ]:
arr5 = np.array([7,8])

In [ ]:
arr5.shape

(2,)

In [ ]:
arr2 + arr5

ValueError: operands could not be broadcast together with shapes (3,3) (2,) 

In [ ]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[2,2,3],[1,2,5]])

In [ ]:
arr1 == arr2

array([[False,  True,  True],
       [False, False, False]])

In [ ]:
arr1 != arr2

array([[ True, False, False],
       [ True,  True,  True]])

In [ ]:
arr1 < arr2

array([[ True, False, False],
       [False, False, False]])

In [ ]:
(arr1 == arr2).sum()

np.int64(2)

In [ ]:
arr3 = np.array([
    [[11, 12, 13, 14],
     [13, 14, 15, 19]],

    [[15, 16, 17, 21],
     [63, 92, 36, 18]],

    [[98, 32, 81, 23],
     [17, 18, 19.5, 43]]])

In [ ]:
arr3.shape

(3, 2, 4)

In [ ]:
arr3[1,1,2]

np.float64(36.0)

In [ ]:
arr3[1:,0:1,:2]

array([[[15., 16.]],

       [[98., 32.]]])

In [ ]:
arr3[1:,1,3]

array([18., 43.])

In [ ]:
arr3[1:, 1, :3]

array([[63. , 92. , 36. ],
       [17. , 18. , 19.5]])

In [ ]:
arr3[1]

array([[15., 16., 17., 21.],
       [63., 92., 36., 18.]])

In [ ]:
arr3[:2]

array([[[11., 12., 13., 14.],
        [13., 14., 15., 19.]],

       [[15., 16., 17., 21.],
        [63., 92., 36., 18.]]])

In [ ]:
arr3[:2,1]

array([[13., 14., 15., 19.],
       [63., 92., 36., 18.]])

In [ ]:
arr3[1,4,3,5]

IndexError: too many indices for array: array is 3-dimensional, but 4 were indexed

In [ ]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [ ]:
np.ones([3,3,3])

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
(np.ones(5))

array([1., 1., 1., 1., 1.])

In [ ]:
np.random.rand(5,2)*10

array([[8.85259925, 3.47317911],
       [6.28069322, 1.70545052],
       [4.64244588, 8.0566647 ],
       [2.43181192, 6.53248594],
       [3.39387976, 5.06761709]])

In [ ]:
np.random.randn(5,2)

array([[ 0.24807869, -0.75142736],
       [-0.73320667,  0.26022174],
       [-0.64714795, -0.80739824],
       [ 0.60275138,  0.72394744],
       [ 0.92706007,  1.34450239]])

In [ ]:
np.full([2,3],42)

array([[42, 42, 42],
       [42, 42, 42]])

In [ ]:
arr1 = np.arange(10,90,3)

In [ ]:
arr1

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88])

In [ ]:
len(arr1)

27

In [ ]:
arr1.reshape(9,3)

array([[10, 13, 16],
       [19, 22, 25],
       [28, 31, 34],
       [37, 40, 43],
       [46, 49, 52],
       [55, 58, 61],
       [64, 67, 70],
       [73, 76, 79],
       [82, 85, 88]])

In [ ]:
arr1.reshape(3,3,3)
#

array([[[10, 13, 16],
        [19, 22, 25],
        [28, 31, 34]],

       [[37, 40, 43],
        [46, 49, 52],
        [55, 58, 61]],

       [[64, 67, 70],
        [73, 76, 79],
        [82, 85, 88]]])

In [ ]:
np.linspace(3,27,9)

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.])